# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'ObjcComponent' do
  pod 'Colours'
  pod 'Masonry'
  pod 'Toast', '~> 3.1.0'
  
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
  
  pod 'JFFoundation'
  pod 'JFUIKit', :git => "https://github.com/jumpingfrog0/JFUIKit.git", :branch => 'master'
  pod 'JFObjcExtension'
  pod 'Masonry'

  # Pods for ObjcComponent

  target 'ObjcComponentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ObjcComponentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
